### ISSUE TITLE
Feedback is not triggered after audio channel volume is changed from Companion

### ISSUE THREAD

**Issue by aaronpk** [bitfocus/companion-module-rode-rcv#3]
To reproduce the error:
* Create a button that sets the volume of an audio channel
* Create feedback on the button that changes the button background based on the set volume
* Press the button

The feedback doesn't run if the volume is changed from Companion. If you change the volume on the RCV itself, then the feedback runs as expected.

![Image](https://github.com/user-attachments/assets/d357563c-9dcb-4628-9c33-57a43bc9ebe4)

![Image](https://github.com/user-attachments/assets/12a5dfcd-6944-4307-bd15-a6ffcc0493de)

**Comment by logicallysynced** [comment]
This is resolved in the next release.
