### ISSUE TITLE
Feature request: Set mute/unmute action

### ISSUE THREAD

**Issue by aaronpk** [bitfocus/companion-module-rode-rcv#4]
Currently there is only an action to toggle the mute state. I would like to see an action that can also set the mute state.

![Image](https://github.com/user-attachments/assets/96bfa756-1e7e-43ee-b60d-8793ac8cbf1b)

I am trying to make some show automation buttons, for example a button to start a countdown timer and a button to start the show. The countdown timer button should set the video clips audio to unmuted and set the mic to muted. The show start button should do the opposite. However right now there is only the "toggle" action, which means I can't create the buttons.

**Comment by logicallysynced** [comment]
This is resolved in the next release.
